// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeIU9KVz-scCd_KNX_CjsUIQl-4zQpmmY',
    appId: '1:117526006924:web:ca9cb1a3ecb0bd4a397fa9',
    messagingSenderId: '117526006924',
    projectId: 'cfasn-service',
    authDomain: 'cfasn-service.firebaseapp.com',
    storageBucket: 'cfasn-service.firebasestorage.app',
    measurementId: 'G-JVBGM168RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD5bVoqnFH3O0rwP3d6-AAdgMHTPwcXFU',
    appId: '1:117526006924:android:efcf1d0ae2a70ee3397fa9',
    messagingSenderId: '117526006924',
    projectId: 'cfasn-service',
    storageBucket: 'cfasn-service.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJRpDLtjYqkWtiPjKqx7t63_t1KcWPEiQ',
    appId: '1:117526006924:ios:57a1307c3ae7b81a397fa9',
    messagingSenderId: '117526006924',
    projectId: 'cfasn-service',
    storageBucket: 'cfasn-service.firebasestorage.app',
    iosBundleId: 'com.example.service',
  );
}
